#!/usr/bin/env bash

if [[ "$1" = "use" && -f "service/${2}/compose.yml" ]];
then 
	rm docker-compose.yml > /dev/null 2>&1
	ln -s service/${2}/compose.yml docker-compose.yml
	shift
	shift
	echo "docker-compose run --service-ports $@ "
	docker-compose run --service-ports $@ 
else 
	echo "Usage 'compose use [service]'"
fi;

